### ISSUE TITLE
Unable to craft Thermal Dynamic's Machine Frame

### ISSUE THREAD

**Issue by karsen777** [Drakma/vacant-sky-3#34]
When attempting to craft a Machine Frame, I am able to load the full recipe into a crafting table or crafting station through JEI or by manually placing the items, but the machine frame does not appear in the to-be-crafted section and you cannot click the area as usual to create the item.

**Comment by Drakma** [comment]
Fixed in latest build

**Comment by karsen777** [comment]
I am still having the same problem with this block, post-steel to invar plate change. Note that I don't think I had to craft it again since the first fix so I can't be sure it hasn't always been broken.

**Comment by Drakma** [comment]
refixed 1.0.8.1
